[theme]
# Primary accent color for interactive elements.
primaryColor = "#dbf5ce"

# Background color for the main content area.
backgroundColor = "#0e4d4d"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#f5c658"

# Color used for almost all text.
textColor = "#fff"
#textColor = "#273133"